ALTER TABLE "Track"
ADD COLUMN "releasedAt" TIMESTAMP(3),
ADD COLUMN "durationMs" INTEGER,
ADD COLUMN "bpm" DOUBLE PRECISION,
ADD COLUMN "explicit" BOOLEAN,
ADD COLUMN "genres" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "moods" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "soundsLikeArtists" JSONB,
ADD COLUMN "story" TEXT,
ADD COLUMN "targetRegion" TEXT;
